// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFL.Context;

namespace NFL.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20211203151827_InitialMigaration")]
    partial class InitialMigaration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("NFL.Models.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AwayFinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayNumberOfTD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeFinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeNumberOfTD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
